name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check out mothertongues
        uses: actions/checkout@v4
        with:
          repository: MotherTongues/mothertongues
          submodules: recursive
          path: mothertongues
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Get poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3.0"
      - name: Install NPM dependencies
        run: |
          # The default config is for the monorepo, while this is for standalone
          cd mothertongues/mothertongues-UI/ && npm install
      - name: Install python dependencies
        run: |
          # The default config is for the monorepo, while this is for standalone
          # TODO: eventually g2p should be removed
          cd mothertongues/mothertongues && poetry install && poetry run pip install g2p
      - name: Compile dictionary data
        run: |
          cd mothertongues/mothertongues && poetry run python cli.py export ../../config.mtd.json ../mothertongues-UI/packages/mtd-mobile-ui/src/assets/
      - name: Test
        run: |
          cd mothertongues/mothertongues-UI && npx nx test search
      - name: Build
        run: |
          cd mothertongues/mothertongues-UI && npx nx build search
          npx nx build mtd-mobile-ui --base-href=/mtd-starter/ --configuration=production
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: mothertongues/mothertongues-UI/dist/packages/mtd-mobile-ui # The folder the action should deploy.